language: node_js
sudo: false
node_js:
  - "6" # to be removed on "April 2019"
  - "8" # to be removed on "December 2019"
  - "10" # to be removed on "April 2021"
before_install:
  - "npm install -g gulp"
  - "npm install -g bower"
  - "npm install -g coveralls"
before_script:
  - "npm run bower"
script:
  - "npm test"
after_success:
  - "npm run coveralls"
