language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
before_install:
  - "npm install -g gulp"
  - "npm install -g bower"
  - "npm install -g coveralls"
before_script:
  - "npm run bower"
script:
  - "npm test"
after_success:
  - "npm run coveralls"
